Project marketplace/PUDDLE/puddle/core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns=[
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login')
]

Project marketplace/PUDDLE/puddle/dashboard/urls.py
from django.urls import path

from . import views

app_name='dashboard'

urlpatterns=[
    path('', views.index, name='index'),
]

Project marketplace/PUDDLE/puddle/item/urls.py
from django.urls import path
from . import views

app_name = 'item'

urlpatterns=[
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('', views.items, name='items'),
]

Project marketplace/PUDDLE/puddle/puddle/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('inbox/', include('conversation.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('items/', include('item.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Project marketplace/PUDDLE/puddle/dashboard/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.decorators import login_required
# Create your views here.
from item.models import Item

@login_required
def index(request):
    items = Item.objects.filter(created_by=request.user)
    
    return render(request, 'dashboard/index.html',{
        'items': items,
    })
    
    

    

Project marketplace/PUDDLE/puddle/dashboard/templates/dashboard/index.html
{% extends 'core/base.html'%}

{%block title%}Dashboard {%endblock%}


{% block content%}
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">My items </h2>

        <div class="grid grid-cols-3 gap-3">
            {%for item in items%}
                <div>
                    <a href="{% url 'item:detail' item.id %}">
                        <div>
                            <img src="{{ item.image.url}}" class="rounded-t-xl">
                        </div>

                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl "> {{item.name }}</h2>
                            <p class="text-gray-500"> Price: {{item.price}}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Categories</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for category in categories %}
            <div>
                <a href="">

                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-2xl "> {{category.name }}</h2>
                        <p class="text-gray-500"> {{ category.items.count }} items</p>
                    </div>
                </a>
            </div>
            {% endfor%}
        </div>
    </div>

{% endblock content%}